import Head from "next/head";
import generatePDF, { Margin } from "react-to-pdf";

const recoverContentToPDF = () => document.getElementById("content-id");

const customization = {
  //Baixar/Salvar = save / Abrir no navegador = open
  method: "open",
  page: {
    // Definir margem: SMALL ou MEDIUM
    margin: Margin.MEDIUM,
    // Formato da página: A4 ou letter
    format: "A4",
    // Orientação do arquivo: portrait ou landscape
    orientation: "portrait",
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Certificado</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => generatePDF(recoverContentToPDF, customization)}>
          Gerar PDF
        </button>

        <div id="content-id">
          <h1 style={{ textAlign: "center", color: "#f00", fontSize: "27px" }}>
            Certificado
          </h1>
        </div>
      </main>
    </>
  );
}
